### PR TITLE
publish logs to cloudwatch

### LINKED ISSUE #227: add logs to sentry
[Sentry](https://github.com/getsentry/sentry) is a pretty cool log aggregator, would allow us to view and search logs in real time.

I'm not sure if we have to host it (eg, add an image to the docker-compose file), and then how we'd actually access the data after that. Worth an investigation at least -- we don't _have to_ use it.

### PR DESCRIPTION
**Pull request by twentylemon**
##### Summary 

Fixes https://github.com/duck-dynasty/duckbot/issues/227. Sentry is apparently free but requires a lot more setup. Plus this puts all the logs in one place.

The `awslogs` driver captures stdout and stderr, which thankfully all logs already write to (byproduct of changes in https://github.com/duck-dynasty/duckbot/pull/381).

I tested manually by creating a new task definition revision in prod (I know, sue me). Logs successfully published to cloudwatch. So huzzah. I'm not 100% on if the yml is valid, but eh. We'll see.

##### Checklist

* [ ] this is a source code change
  * [ ] run `isort . && black .` in the repository root
  * [ ] run `pytest` in the repository root
  * [ ] link to issue being fixed using a [_fixes keyword_](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue), if such an issue exists
  * [ ] update the wiki documentation if necessary
* [x] or, this is **not** a source code change

### CODE REVIEW

**Comment by Chippers255** [comment]
Brother, I am going to need access to this cloud watch, you should be able to give me a user account then grant me cloud watch access in IAM.

**Comment by Chippers255** [comment]
Side note, SNS is so cheap it is basically free, configured correctly then it can notify us on Discord or via email/sms when shit goes wrong on ECS. I have configured something like this previously.

**Comment by twentylemon** [comment]
I can create a user for you today.

For for SNS, cloudwatch alarms are also free (iirc 10 alarms), so we can use that as well (an alarm action can be publishing to a topic). Container health checks already happen, ecs should take care of that, but we can still monitor the ec2 instance, and look for too many container starts or something.

**Comment by twentylemon** [comment]
> Side note, SNS is so cheap it is basically free, configured correctly then it can notify us on Discord or via email/sms when shit goes wrong on ECS. I have configured something like this previously.

https://github.com/duck-dynasty/duckbot/issues/384, think it's outside the scope of this change.

**Review by Chippers255 — APPROVED** [review]

**Pull request merged**
