### PR TITLE
add Duckbot advertisement video to readme

### LINKED ISSUE #324: Add the fancy video to the readme
@Chippers255 knows what he must do.

### PR DESCRIPTION
**Pull request by Chippers255**
##### Summary 

This one is pretty simple, I uploaded the advert for Duckbot to the readme. Turns out you can just drag and drop a video file into the markdown editor on github. We can't hide the file name so let me know if we should change it. This will close out issue #324.

##### Checklist

* [ ] this is a source code change
  * [ ] run `isort . && black .` in the repository root
  * [ ] run `pytest` in the repository root
  * [ ] link to issue being fixed using a [_fixes keyword_](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue), if such an issue exists
  * [ ] update the wiki documentation if necessary
* [x] or, this is **not** a source code change

### CODE REVIEW

**Review by twentylemon — COMMENTED** [review]
Any way to resize it to be a bit smaller? It's a bit chonky.

Would also be nice to rename it so it doesn't say `Duckbot_Final.mp4` at the top. Maybe `duckbot.mp4` or `DuckBot.mp4` since the filename has to show up.

https://github.com/duck-dynasty/duckbot/blob/dc4685ec91c0c0bbd279e80a4c90a5a51e1c20d5/README.md

**Comment by Chippers255** [comment]
The documentation doesn't show a way to adjust the size of the video.

**Comment by Chippers255** [comment]
[Video linking documentation](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/attaching-files). You can adjust images with HTML. It doesn't seem the videos work the same way.

**Review by twentylemon — APPROVED** [review]

**Comment by zambon** [comment]
>It's a bit chonky.

🚢-it conditional on making it chonkier.

**Comment by twentylemon** [comment]
never

**Pull request merged**
