### PR TITLE
DuckBot now announces its presence

### PR DESCRIPTION
**Pull request by Chippers255**

### CODE REVIEW

**Comment by twentylemon** [comment]
I'm against this change. I don't really want noise for the sake of noise.

**Comment by Chippers255** [comment]
I figured until the bot is hosted it would be good to know when it is online. What about pushing this message to the DuckButt channel?

**Comment by twentylemon** [comment]
Posting to #duckbutt is fine I suppose. At some point though, the bot will always be online; announcing it's presence is moot. I'd rather avoid useless noise for no real reason.

**Comment by Chippers255** [comment]
Fair enough, I will revert.

**Comment by jameshughes89** [comment]
Fucking engineers

**Comment by twentylemon** [comment]
Rude.

**Pull request merged**
