### PR TITLE
Change to `pytest-flake8-v2`

### LINKED ISSUE #666: try out `pytest-flake8-v2`
`pytest-flake8` seems to be [dead](https://github.com/tholo/pytest-flake8/issues/91), with the owner not even showing up to say that people that want to take over the project can.

The issue above indirectly mentions this [fork](https://github.com/VRGhost/pytest-flake8) which is published as [pytest-flake8-v2](https://pypi.org/project/pytest-flake8-v2/). I imagine it's meant to be a drop in replacement but have not done any real research past finding the project.

### PR DESCRIPTION
**Pull request by jameshughes89**
##### Summary

Closes #666 

Switch out `pytest-flake8` for `pytest-flake8-v2`

**NOTE:**
- I got a funny warning message when running setup with the new package, but it seemed to install properly anyways
- Several tests failed locally (something about mock not being subscriptable), but I think that's a _me_ issue that may have been caused by using python 3.11. I wanna' see what the actions say. 

##### Checklist

- [x] this is a source code change
  - [x] run `format` in the repository root
  - [x] run `pytest` in the repository root
  - [x] link to issue being fixed using a [_fixes keyword_](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue), if such an issue exists
  - [ ] update the wiki documentation if necessary
- [ ] or, this is **not** a source code change

### CODE REVIEW

**Comment by twentylemon** [comment]
> * caused by using python 3.11

bruh. `venv` lets you have many python's installed at once. why are you using a version duckbot is not :thinking:

**Comment by twentylemon** [comment]
Tests seem fine -- number of tests also seems fine, I recall seeing ~1300 during the dependabot upgrades. I'd like to see some evidence that it actually catches flake8 errors before approval though.

**Comment by jameshughes89** [comment]
If it explodes, I blame whoever merges.

**Comment by jameshughes89** [comment]
> Tests seem fine -- number of tests also seems fine, I recall seeing ~1300 during the dependabot upgrades. I'd like to see some evidence that it actually catches flake8 errors before approval though.

I'll check this out

**Comment by jameshughes89** [comment]
1. I ran tests on python3,8 and everything worked good

image

2. I added a bunch of newlines to `duck.py`

image

3. I re-ran tests and it freaked out

image

Huzzah

**Comment by twentylemon** [comment]
Nice. Even has the actual flake errors, we stopped getting those a while back and just getting a generic failure.

**Review by twentylemon — APPROVED** [review]

**Comment by jameshughes89** [comment]
Now for the real test --- how will it do with #637

**Pull request merged**
