### PR TITLE
correct @mock.patch argument order

### PR DESCRIPTION
**Pull request by twentylemon**
##### Summary 

Title. While working on slash commands stuff, I noticed this. Bottom first for @mock.patch! ([scroll down a bit here](https://docs.python.org/3/library/unittest.mock.html#quick-guide)) Tiny PR to fix it.

##### Checklist

* [x] this is a source code change
  * [x] run `isort . && black .` in the repository root
  * [x] run `pytest` in the repository root
  * [x] link to issue being fixed using a [_fixes keyword_](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue), if such an issue exists
  * [x] update the wiki documentation if necessary
* [ ] or, this is **not** a source code change

### CODE REVIEW

**Review by jameshughes89 — APPROVED** [review]

**Comment by jameshughes89** [comment]
On phone, so searching is annoying, but this note was brought up months ago in a PR comment or something. Sneaky sneaky thing.

**Comment by jameshughes89** [comment]
Looks like #223 & #224

**Comment by twentylemon** [comment]
> On phone, so searching is annoying, but this note was brought up months ago in a PR comment or something. Sneaky sneaky thing.

Yeah. Problem is it applies in the opposite order you'd expect regular function calls to work. `first(second(func))` is the expectation, which would evaluate `second` first, modifying the function by putting the argument, then `first` would operate on that new function, thus making the args appear top first. But they appear bottom first. So like. Yeah.

**Comment by jameshughes89** [comment]
> > On phone, so searching is annoying, but this note was brought up months ago in a PR comment or something. Sneaky sneaky thing.
> 
> Yeah. Problem is it applies in the opposite order you'd expect regular function calls to work. `first(second(func))` is the expectation, which would evaluate `second` first, modifying the function by putting the argument, then `first` would operate on that new function, thus making the args appear top first. But they appear bottom first. So like. Yeah.

I gottcha'.

**Pull request merged**
