### PR TITLE
👷 replace LGTM scanning with codeql

### PR DESCRIPTION
**Pull request by twentylemon**
##### Summary

LGTM is [shutting down](https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/) unfortunately. The scanning part of it can be replaced by [CodeQL](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/setting-up-code-scanning-for-a-repository#setting-up-code-scanning-using-actions), which is the same set of tools but in a different place, pretty much.

We also lose our LGTM code quality badge. Lest we forget.

##### Checklist

- [ ] this is a source code change
  - [ ] run `format` in the repository root
  - [ ] run `pytest` in the repository root
  - [ ] link to issue being fixed using a [_fixes keyword_](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue), if such an issue exists
  - [ ] update the wiki documentation if necessary
- [x] or, this is **not** a source code change

### CODE REVIEW

**Comment by jameshughes89** [comment]
Did you end up doing it with [point and click](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/setting-up-code-scanning-for-a-repository#setting-up-code-scanning-using-starter-workflows), or did you just build the yml yourself?

**Comment by twentylemon** [comment]
> Did you end up doing it with [point and click](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/setting-up-code-scanning-for-a-repository#setting-up-code-scanning-using-starter-workflows), or did you just build the yml yourself?

I copied the yml from the web UI then editted it a bit. It contained a lot of needless work (like a language matrix). Otherwise, it's the same file as what the generate automatically.

**Comment by twentylemon** [comment]
Also probably worth mentioning that I ran this on my fork, in a recently closed pull request there.

**Review by jameshughes89 — APPROVED** [review]
Seems nice and simple as a new workflow.

**Pull request merged**
