### PR TITLE
:lipstick: change the weather graph to have xkcd styling

### PR DESCRIPTION
**Pull request by Chippers255**
I think the weather graph should be a little more fun. They are too serious for the nature of DuckButt.

### CODE REVIEW

**Comment by twentylemon** [comment]
Can you run some tests in beta? From what I tested locally (during original development), it rendered horribly.

**Comment by jameshughes89** [comment]
Anyone get to them beta tests to see how pretty or uggo they be?

**Comment by twentylemon** [comment]
> Anyone get to them beta tests to see how pretty or uggo they be?

Defo a @Chippers255 task.

**Comment by twentylemon** [comment]
@Chippers255 any luck?

**Comment by jameshughes89** [comment]
@Chippers255 any luck?

**Comment by jameshughes89** [comment]
Yo, @Chippers255, this looks neat.

**Comment by twentylemon** [comment]
@Chippers255 have you accomplished this herculean task?

**Comment by jameshughes89** [comment]
> @Chippers255 have you accomplished this herculean task?

I saw activity. I got excited. Was disappointed.

**Comment by twentylemon** [comment]
@Chippers255 I believe.

**Comment by jameshughes89** [comment]
hi

**Comment by twentylemon** [comment]
image

:headstone:

**Comment by twentylemon** [comment]
@Chippers255 given the conflict, I think the joke has run it's course. Get some traction, or duckbot will never see the light of xkcd again. Attaching `needs reply`.

**Comment by jameshughes89** [comment]
🕚

**Pull request closed without merging**
