### PR TITLE
rename tests from `test_blah` to `blah_test`

### PR DESCRIPTION
**Pull request by twentylemon**
##### Summary 

I'm kinda annoyed by the test file names. So I changed them. `test_blah` is more annoying:
* it's not how you talk
* tab completion is harder since everything is `test_`

I ran:

```sh
for x in $(find tests/ -name 'test*.py'); do y=${x/test_/}; mv $x ${y%.py}_test.py; done
```

Unfortunately, pytest still requires test functions to be named `test_unit`, but the file names can go either way.

##### Checklist

* [x] this is a source code change
  * [x] run `isort . && black .` in the repository root
  * [x] run `pytest` in the repository root
  * [x] link to issue being fixed using a [_fixes keyword_](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue), if such an issue exists
  * [x] update the wiki documentation if necessary
* [ ] or, this is **not** a source code change

### CODE REVIEW

**Review by jameshughes89 — APPROVED** [review]
Cool.

Won't squish until there's consensus?

**Comment by twentylemon** [comment]
> Cool.
> 
> Won't squish until there's consensus?

@Chippers255 then, thoughts?

**Comment by jameshughes89** [comment]
> > Cool.
> > 
> > Won't squish until there's consensus?
> 
> @Chippers255 then, thoughts?

Yo, @Chippers255, my man.

**Comment by twentylemon** [comment]
> > > Cool.
> > > Won't squish until there's consensus?
> > 
> > 
> > @Chippers255 then, thoughts?
> 
> Yo, @Chippers255, my man.

Yo, my man, @Chippers255.

**Comment by Chippers255** [comment]
> > > > Cool.
> > > > Won't squish until there's consensus?
> > > 
> > > 
> > > @Chippers255 then, thoughts?
> > 
> > 
> > Yo, @Chippers255, my man.
> 
> Yo, my man, @Chippers255.
Yo, my man, @Chippers255.

**Comment by Chippers255** [comment]
I have no preference either way, as long as the run. LGTM

**Review by Chippers255 — APPROVED** [review]

**Pull request merged**
